Fix #8: Tests suite
DrPlumcake/super-sast-artifact pull request #9
Opened 2023-11-11 17:37 UTC by DrPlumcake

2023-11-13 15:02 UTC, ioggstream requested changes
@DrPlumcake Generally ok provided the following suggestions.

:warning: don't override `dict` and other built-in classes!

2023-11-13 15:02 UTC, ioggstream commented on Dockerfile
>  RUN chmod +x /parse_scripts/*
We don't need it
```suggestion
```

2023-11-13 15:02 UTC, ioggstream commented on Dockerfile
> +COPY tests /
We don't need tests in our container.

2023-11-13 15:02 UTC, ioggstream commented on main.py
> +def env_json(dict, tool, environ=environ):
Don't override the `dict` class :) 
A variable name should describe its content, not its type.

2023-11-13 15:02 UTC, ioggstream commented on main.py
> +    value_tool = dict.get(tool, "None")
Why are you checking for the string "None" ?

2023-11-13 15:02 UTC, ioggstream commented on main.py
> +            log.setLevel(logging.DEBUG)
An application should not modify its logging level. The caller must decide the logging level.

2023-11-13 15:02 UTC, ioggstream commented on tests/test_bandit.py
>      assert annotations[0]["path"] == "canary.py"
OK!

2023-11-13 15:02 UTC, ioggstream commented on tests/test_checkov.py
> +    expected_comments = {
OK, but this can even go in a separate test file.

2023-11-13 18:19 UTC, DrPlumcake commented
@ioggstream "test_errors" of test_bandit.py still goes into failure. Suggestions?

2023-11-14 11:05 UTC, DrPlumcake commented
`Syntax Error` does not have anymore `"invalid syntax"` string in the `args` parameter (i checked).
So, if code catches a syntax error, we directly write in the title of the error the string "invalid syntax"

2023-11-14 11:26 UTC, merged